### ISSUE TITLE
New release 0.8.0

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/napari-clusters-plotter#281]
Hi all,

I was wondering if we could make a new plugin release before implementing larger changes like other layer types and plotter re-designs.

I created the milestone `0.7.4` and assigned it to a couple PRs whose changes are minimal and here.

Anything major we need to test before releasing it?

Best,
Marcelo

**Comment by zoccoler** [comment]
By the way, is other layer types support already in main?

**Comment by haesleinhuepf** [comment]
Also, at the momemt only Laura, Ryan and I can deploy releases to pypi and conda. Would it be ok for you if I add you there @zoccoler ?

**Comment by Cryaaa** [comment]
That would be a good idea! Both the release and adding @zoccoler !

**Comment by Cryaaa** [comment]
> By the way, is other layer types support already in main?

Yep that change is already in main!

**Comment by thorstenwagner** [comment]
Really looking forward to a new release to have PR #283 and #282 in place :-)

**Comment by thorstenwagner** [comment]
Look like this issue is the only left over issue for the 0.7.4 milestone. Release it?

**Comment by haesleinhuepf** [comment]
The old procedure doesn't work anymore. Pypi is now forcing us to use API tokens. [This page](https://pypi.org/help/#apitoken) might be an entry point).

Before releasing 0.7.4, please make sure all changes (in particular to the API) are backwards compatible. If this is not the case, consider releasing 0.8.0 instead. See also: [semantic versioning](https://semver.org/).

**Comment by haesleinhuepf** [comment]
Also before releasing a new version, would someone volunteer for testing the current version carefully? I just found #295 is making usage more complicated compared to 0.7.3 . It would be great if the user-convenience does not suffer from introducing new features. ;-)

**Comment by thorstenwagner** [comment]
I would also like to see #298 merged before release, because its very annoying in my use case :-)

**Comment by jo-mueller** [comment]
As for the PyPi isse - whose PyPi account is currently used for the release? Setting up the API tokens for automatic push and release through PyPi is not difficult, but the owner of the package on PyPi has to generate one. According to the PyPi page, @Cryaaa @haesleinhuepf and @lazigu are owners 🤔

**Comment by haesleinhuepf** [comment]
> Setting up the API tokens for automatic push and release through PyPi is not difficult,

I suggest setting up a github issue for this so that we don't forget to do this.

**Comment by jo-mueller** [comment]
@haesleinhuepf The cookiecutter template for napari-plugins [essentially already has it](https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/.github/workflows/test_and_deploy.yml). The relevant part is this bit in the `test_and_deploy.yaml` in the workflows folder:

```yaml
  deploy:
    # this will run when you have tagged a commit, starting with "v*"
    # and requires that you have put your twine API key in your
    # github secrets (see readme for details)
    needs: [test]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools setuptools_scm wheel twine build
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          git tag
          python -m build .
          twine upload dist/*
```

Once that is set up, there only needs to be a valid API token with the name `PYPI_API_TOKEN ` in the secrets of the repository that is to be published. Doing a release on github then automatically runs the deployment to github.
